spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/mybatis_test?serverTimezone=GMT%2B8
     username: root
     password: 12345678
     driverClassName: com.mysql.cj.jdbc.Driver
     max-idle: 10
     max-wait: 10000
     min-idle: 5
     initial-size: 5
     server.tomcat.uri-encoding: UTF-8

mybatis:
  mapper-locations: classpath:Mapping/MessageMapper.xml

  configuration:
     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl